// tslint:disable
// this is an auto generated file. This will be overwritten

export const onCreateNoticePost = `subscription OnCreateNoticePost {
  onCreateNoticePost {
    id
    body
    comments {
      id
      body
      date
      postId
      author {
        birthdate
        snsLogin
        email
        email_verified
        name
        phone_number
        avatar
        level
      }
    }
    author {
      birthdate
      snsLogin
      email
      email_verified
      name
      phone_number
      posts
      avatar
      level
    }
    date
    headerImgSrc
    isLike
    issueName
    numComments
    numLikes
    numShares
    themeColor
    title
    topics
    whoLike {
      birthdate
      snsLogin
      email
      email_verified
      name
      phone_number
      posts
      avatar
      level
    }
  }
}
`;
export const onUpdateNoticePost = `subscription OnUpdateNoticePost {
  onUpdateNoticePost {
    id
    body
    comments {
      id
      body
      date
      postId
      author {
        birthdate
        snsLogin
        email
        email_verified
        name
        phone_number
        avatar
        level
      }
    }
    author {
      birthdate
      snsLogin
      email
      email_verified
      name
      phone_number
      posts
      avatar
      level
    }
    date
    headerImgSrc
    isLike
    issueName
    numComments
    numLikes
    numShares
    themeColor
    title
    topics
    whoLike {
      birthdate
      snsLogin
      email
      email_verified
      name
      phone_number
      posts
      avatar
      level
    }
  }
}
`;
export const onDeleteNoticePost = `subscription OnDeleteNoticePost {
  onDeleteNoticePost {
    id
    body
    comments {
      id
      body
      date
      postId
      author {
        birthdate
        snsLogin
        email
        email_verified
        name
        phone_number
        avatar
        level
      }
    }
    author {
      birthdate
      snsLogin
      email
      email_verified
      name
      phone_number
      posts
      avatar
      level
    }
    date
    headerImgSrc
    isLike
    issueName
    numComments
    numLikes
    numShares
    themeColor
    title
    topics
    whoLike {
      birthdate
      snsLogin
      email
      email_verified
      name
      phone_number
      posts
      avatar
      level
    }
  }
}
`;
export const onCreateFreePost = `subscription OnCreateFreePost {
  onCreateFreePost {
    id
    body
    comments {
      id
      body
      date
      postId
      author {
        birthdate
        snsLogin
        email
        email_verified
        name
        phone_number
        avatar
        level
      }
    }
    author {
      birthdate
      snsLogin
      email
      email_verified
      name
      phone_number
      posts
      avatar
      level
    }
    date
    headerImgSrc
    isLike
    issueName
    numComments
    numLikes
    numShares
    themeColor
    title
    topics
    whoLike {
      birthdate
      snsLogin
      email
      email_verified
      name
      phone_number
      posts
      avatar
      level
    }
  }
}
`;
export const onUpdateFreePost = `subscription OnUpdateFreePost {
  onUpdateFreePost {
    id
    body
    comments {
      id
      body
      date
      postId
      author {
        birthdate
        snsLogin
        email
        email_verified
        name
        phone_number
        avatar
        level
      }
    }
    author {
      birthdate
      snsLogin
      email
      email_verified
      name
      phone_number
      posts
      avatar
      level
    }
    date
    headerImgSrc
    isLike
    issueName
    numComments
    numLikes
    numShares
    themeColor
    title
    topics
    whoLike {
      birthdate
      snsLogin
      email
      email_verified
      name
      phone_number
      posts
      avatar
      level
    }
  }
}
`;
export const onDeleteFreePost = `subscription OnDeleteFreePost {
  onDeleteFreePost {
    id
    body
    comments {
      id
      body
      date
      postId
      author {
        birthdate
        snsLogin
        email
        email_verified
        name
        phone_number
        avatar
        level
      }
    }
    author {
      birthdate
      snsLogin
      email
      email_verified
      name
      phone_number
      posts
      avatar
      level
    }
    date
    headerImgSrc
    isLike
    issueName
    numComments
    numLikes
    numShares
    themeColor
    title
    topics
    whoLike {
      birthdate
      snsLogin
      email
      email_verified
      name
      phone_number
      posts
      avatar
      level
    }
  }
}
`;
export const onCreateProjectPost = `subscription OnCreateProjectPost {
  onCreateProjectPost {
    id
    project {
      id
      proposer {
        birthdate
        snsLogin
        email
        email_verified
        name
        phone_number
        avatar
        level
        position
      }
      name
      description
      types
      topics
      deadlineOption
      startDuration
      endDuration
      manager
      personnel
      hasPlace
      place
      studyTopics
      studyMeeting
      studyTutor
      contestTopic
      contestProductDescription
      contestName
      contestDuedate
      contestObjectives
      seminarTopics
      seminarIsOnce
      seminarMeeting
      seminarPresenter
      shareCopyright
      agileHasBeen
      etcDescription
      request {
        id
        cProjectId
        date
        hopePlaces
        material
        budget
        cookie
        extra
        status
      }
      activities {
        id
        projectName
        date
        type
        description
      }
      contributors {
        birthdate
        snsLogin
        email
        email_verified
        name
        phone_number
        avatar
        level
        position
      }
      comments {
        id
        body
        date
        postId
        cProjectId
      }
      contents {
        id
        body
        date
        headerImgSrc
        isLike
        issueName
        numComments
        numLikes
        numShares
        themeColor
        title
        topics
      }
      fixedBudget
      pictures {
        body
        date
        src
        title
        numComments
        numLikes
        numShares
        topics
      }
      supports {
        id
        cProjectId
        date
        status
        title
        description
      }
      status
      syncGithub
      themeColor
    }
    body
    comments {
      id
      body
      date
      postId
      author {
        birthdate
        snsLogin
        email
        email_verified
        name
        phone_number
        avatar
        level
      }
    }
    author {
      birthdate
      snsLogin
      email
      email_verified
      name
      phone_number
      posts
      avatar
      level
    }
    date
    headerImgSrc
    isLike
    issueName
    numComments
    numLikes
    numShares
    themeColor
    title
    topics
    whoLike {
      birthdate
      snsLogin
      email
      email_verified
      name
      phone_number
      posts
      avatar
      level
    }
    contributors {
      birthdate
      snsLogin
      email
      email_verified
      name
      phone_number
      posts
      avatar
      level
      position
    }
  }
}
`;
export const onUpdateProjectPost = `subscription OnUpdateProjectPost {
  onUpdateProjectPost {
    id
    project {
      id
      proposer {
        birthdate
        snsLogin
        email
        email_verified
        name
        phone_number
        avatar
        level
        position
      }
      name
      description
      types
      topics
      deadlineOption
      startDuration
      endDuration
      manager
      personnel
      hasPlace
      place
      studyTopics
      studyMeeting
      studyTutor
      contestTopic
      contestProductDescription
      contestName
      contestDuedate
      contestObjectives
      seminarTopics
      seminarIsOnce
      seminarMeeting
      seminarPresenter
      shareCopyright
      agileHasBeen
      etcDescription
      request {
        id
        cProjectId
        date
        hopePlaces
        material
        budget
        cookie
        extra
        status
      }
      activities {
        id
        projectName
        date
        type
        description
      }
      contributors {
        birthdate
        snsLogin
        email
        email_verified
        name
        phone_number
        avatar
        level
        position
      }
      comments {
        id
        body
        date
        postId
        cProjectId
      }
      contents {
        id
        body
        date
        headerImgSrc
        isLike
        issueName
        numComments
        numLikes
        numShares
        themeColor
        title
        topics
      }
      fixedBudget
      pictures {
        body
        date
        src
        title
        numComments
        numLikes
        numShares
        topics
      }
      supports {
        id
        cProjectId
        date
        status
        title
        description
      }
      status
      syncGithub
      themeColor
    }
    body
    comments {
      id
      body
      date
      postId
      author {
        birthdate
        snsLogin
        email
        email_verified
        name
        phone_number
        avatar
        level
      }
    }
    author {
      birthdate
      snsLogin
      email
      email_verified
      name
      phone_number
      posts
      avatar
      level
    }
    date
    headerImgSrc
    isLike
    issueName
    numComments
    numLikes
    numShares
    themeColor
    title
    topics
    whoLike {
      birthdate
      snsLogin
      email
      email_verified
      name
      phone_number
      posts
      avatar
      level
    }
    contributors {
      birthdate
      snsLogin
      email
      email_verified
      name
      phone_number
      posts
      avatar
      level
      position
    }
  }
}
`;
export const onDeleteProjectPost = `subscription OnDeleteProjectPost {
  onDeleteProjectPost {
    id
    project {
      id
      proposer {
        birthdate
        snsLogin
        email
        email_verified
        name
        phone_number
        avatar
        level
        position
      }
      name
      description
      types
      topics
      deadlineOption
      startDuration
      endDuration
      manager
      personnel
      hasPlace
      place
      studyTopics
      studyMeeting
      studyTutor
      contestTopic
      contestProductDescription
      contestName
      contestDuedate
      contestObjectives
      seminarTopics
      seminarIsOnce
      seminarMeeting
      seminarPresenter
      shareCopyright
      agileHasBeen
      etcDescription
      request {
        id
        cProjectId
        date
        hopePlaces
        material
        budget
        cookie
        extra
        status
      }
      activities {
        id
        projectName
        date
        type
        description
      }
      contributors {
        birthdate
        snsLogin
        email
        email_verified
        name
        phone_number
        avatar
        level
        position
      }
      comments {
        id
        body
        date
        postId
        cProjectId
      }
      contents {
        id
        body
        date
        headerImgSrc
        isLike
        issueName
        numComments
        numLikes
        numShares
        themeColor
        title
        topics
      }
      fixedBudget
      pictures {
        body
        date
        src
        title
        numComments
        numLikes
        numShares
        topics
      }
      supports {
        id
        cProjectId
        date
        status
        title
        description
      }
      status
      syncGithub
      themeColor
    }
    body
    comments {
      id
      body
      date
      postId
      author {
        birthdate
        snsLogin
        email
        email_verified
        name
        phone_number
        avatar
        level
      }
    }
    author {
      birthdate
      snsLogin
      email
      email_verified
      name
      phone_number
      posts
      avatar
      level
    }
    date
    headerImgSrc
    isLike
    issueName
    numComments
    numLikes
    numShares
    themeColor
    title
    topics
    whoLike {
      birthdate
      snsLogin
      email
      email_verified
      name
      phone_number
      posts
      avatar
      level
    }
    contributors {
      birthdate
      snsLogin
      email
      email_verified
      name
      phone_number
      posts
      avatar
      level
      position
    }
  }
}
`;
export const onCreateComment = `subscription OnCreateComment {
  onCreateComment {
    id
    body
    date
    postId
    author {
      birthdate
      snsLogin
      email
      email_verified
      name
      phone_number
      posts
      avatar
      level
    }
  }
}
`;
export const onUpdateComment = `subscription OnUpdateComment {
  onUpdateComment {
    id
    body
    date
    postId
    author {
      birthdate
      snsLogin
      email
      email_verified
      name
      phone_number
      posts
      avatar
      level
    }
  }
}
`;
export const onDeleteComment = `subscription OnDeleteComment {
  onDeleteComment {
    id
    body
    date
    postId
    author {
      birthdate
      snsLogin
      email
      email_verified
      name
      phone_number
      posts
      avatar
      level
    }
  }
}
`;
export const onCreateProjectComment = `subscription OnCreateProjectComment {
  onCreateProjectComment {
    id
    body
    date
    postId
    cProjectId
    project {
      id
      proposer {
        birthdate
        snsLogin
        email
        email_verified
        name
        phone_number
        avatar
        level
        position
      }
      name
      description
      types
      topics
      deadlineOption
      startDuration
      endDuration
      manager
      personnel
      hasPlace
      place
      studyTopics
      studyMeeting
      studyTutor
      contestTopic
      contestProductDescription
      contestName
      contestDuedate
      contestObjectives
      seminarTopics
      seminarIsOnce
      seminarMeeting
      seminarPresenter
      shareCopyright
      agileHasBeen
      etcDescription
      request {
        id
        cProjectId
        date
        hopePlaces
        material
        budget
        cookie
        extra
        status
      }
      activities {
        id
        projectName
        date
        type
        description
      }
      contributors {
        birthdate
        snsLogin
        email
        email_verified
        name
        phone_number
        avatar
        level
        position
      }
      comments {
        id
        body
        date
        postId
        cProjectId
      }
      contents {
        id
        body
        date
        headerImgSrc
        isLike
        issueName
        numComments
        numLikes
        numShares
        themeColor
        title
        topics
      }
      fixedBudget
      pictures {
        body
        date
        src
        title
        numComments
        numLikes
        numShares
        topics
      }
      supports {
        id
        cProjectId
        date
        status
        title
        description
      }
      status
      syncGithub
      themeColor
    }
    author {
      birthdate
      snsLogin
      email
      email_verified
      name
      phone_number
      posts
      avatar
      level
      position
    }
  }
}
`;
export const onUpdateProjectComment = `subscription OnUpdateProjectComment {
  onUpdateProjectComment {
    id
    body
    date
    postId
    cProjectId
    project {
      id
      proposer {
        birthdate
        snsLogin
        email
        email_verified
        name
        phone_number
        avatar
        level
        position
      }
      name
      description
      types
      topics
      deadlineOption
      startDuration
      endDuration
      manager
      personnel
      hasPlace
      place
      studyTopics
      studyMeeting
      studyTutor
      contestTopic
      contestProductDescription
      contestName
      contestDuedate
      contestObjectives
      seminarTopics
      seminarIsOnce
      seminarMeeting
      seminarPresenter
      shareCopyright
      agileHasBeen
      etcDescription
      request {
        id
        cProjectId
        date
        hopePlaces
        material
        budget
        cookie
        extra
        status
      }
      activities {
        id
        projectName
        date
        type
        description
      }
      contributors {
        birthdate
        snsLogin
        email
        email_verified
        name
        phone_number
        avatar
        level
        position
      }
      comments {
        id
        body
        date
        postId
        cProjectId
      }
      contents {
        id
        body
        date
        headerImgSrc
        isLike
        issueName
        numComments
        numLikes
        numShares
        themeColor
        title
        topics
      }
      fixedBudget
      pictures {
        body
        date
        src
        title
        numComments
        numLikes
        numShares
        topics
      }
      supports {
        id
        cProjectId
        date
        status
        title
        description
      }
      status
      syncGithub
      themeColor
    }
    author {
      birthdate
      snsLogin
      email
      email_verified
      name
      phone_number
      posts
      avatar
      level
      position
    }
  }
}
`;
export const onDeleteProjectComment = `subscription OnDeleteProjectComment {
  onDeleteProjectComment {
    id
    body
    date
    postId
    cProjectId
    project {
      id
      proposer {
        birthdate
        snsLogin
        email
        email_verified
        name
        phone_number
        avatar
        level
        position
      }
      name
      description
      types
      topics
      deadlineOption
      startDuration
      endDuration
      manager
      personnel
      hasPlace
      place
      studyTopics
      studyMeeting
      studyTutor
      contestTopic
      contestProductDescription
      contestName
      contestDuedate
      contestObjectives
      seminarTopics
      seminarIsOnce
      seminarMeeting
      seminarPresenter
      shareCopyright
      agileHasBeen
      etcDescription
      request {
        id
        cProjectId
        date
        hopePlaces
        material
        budget
        cookie
        extra
        status
      }
      activities {
        id
        projectName
        date
        type
        description
      }
      contributors {
        birthdate
        snsLogin
        email
        email_verified
        name
        phone_number
        avatar
        level
        position
      }
      comments {
        id
        body
        date
        postId
        cProjectId
      }
      contents {
        id
        body
        date
        headerImgSrc
        isLike
        issueName
        numComments
        numLikes
        numShares
        themeColor
        title
        topics
      }
      fixedBudget
      pictures {
        body
        date
        src
        title
        numComments
        numLikes
        numShares
        topics
      }
      supports {
        id
        cProjectId
        date
        status
        title
        description
      }
      status
      syncGithub
      themeColor
    }
    author {
      birthdate
      snsLogin
      email
      email_verified
      name
      phone_number
      posts
      avatar
      level
      position
    }
  }
}
`;
export const onCreateProject = `subscription OnCreateProject {
  onCreateProject {
    id
    proposer {
      birthdate
      snsLogin
      email
      email_verified
      name
      phone_number
      posts
      avatar
      level
      position
    }
    name
    description
    types
    topics
    deadlineOption
    startDuration
    endDuration
    manager
    personnel
    hasPlace
    place
    studyTopics
    studyMeeting
    studyTutor
    contestTopic
    contestProductDescription
    contestName
    contestDuedate
    contestObjectives
    seminarTopics
    seminarIsOnce
    seminarMeeting
    seminarPresenter
    shareCopyright
    agileHasBeen
    etcDescription
    request {
      id
      cProjectId
      project {
        id
        name
        description
        types
        topics
        deadlineOption
        startDuration
        endDuration
        manager
        personnel
        hasPlace
        place
        studyTopics
        studyMeeting
        studyTutor
        contestTopic
        contestProductDescription
        contestName
        contestDuedate
        contestObjectives
        seminarTopics
        seminarIsOnce
        seminarMeeting
        seminarPresenter
        shareCopyright
        agileHasBeen
        etcDescription
        fixedBudget
        status
        syncGithub
        themeColor
      }
      date
      requester {
        birthdate
        snsLogin
        email
        email_verified
        name
        phone_number
        avatar
        level
        position
      }
      hopePlaces
      material
      budget
      cookie
      extra
      status
    }
    activities {
      id
      projectName
      date
      type
      description
      contributors {
        birthdate
        snsLogin
        email
        email_verified
        name
        phone_number
        avatar
        level
        position
      }
    }
    contributors {
      birthdate
      snsLogin
      email
      email_verified
      name
      phone_number
      posts
      avatar
      level
      position
    }
    comments {
      id
      body
      date
      postId
      cProjectId
      project {
        id
        name
        description
        types
        topics
        deadlineOption
        startDuration
        endDuration
        manager
        personnel
        hasPlace
        place
        studyTopics
        studyMeeting
        studyTutor
        contestTopic
        contestProductDescription
        contestName
        contestDuedate
        contestObjectives
        seminarTopics
        seminarIsOnce
        seminarMeeting
        seminarPresenter
        shareCopyright
        agileHasBeen
        etcDescription
        fixedBudget
        status
        syncGithub
        themeColor
      }
      author {
        birthdate
        snsLogin
        email
        email_verified
        name
        phone_number
        avatar
        level
        position
      }
    }
    contents {
      id
      project {
        id
        name
        description
        types
        topics
        deadlineOption
        startDuration
        endDuration
        manager
        personnel
        hasPlace
        place
        studyTopics
        studyMeeting
        studyTutor
        contestTopic
        contestProductDescription
        contestName
        contestDuedate
        contestObjectives
        seminarTopics
        seminarIsOnce
        seminarMeeting
        seminarPresenter
        shareCopyright
        agileHasBeen
        etcDescription
        fixedBudget
        status
        syncGithub
        themeColor
      }
      body
      comments {
        id
        body
        date
        postId
      }
      author {
        birthdate
        snsLogin
        email
        email_verified
        name
        phone_number
        avatar
        level
      }
      date
      headerImgSrc
      isLike
      issueName
      numComments
      numLikes
      numShares
      themeColor
      title
      topics
      whoLike {
        birthdate
        snsLogin
        email
        email_verified
        name
        phone_number
        avatar
        level
      }
      contributors {
        birthdate
        snsLogin
        email
        email_verified
        name
        phone_number
        avatar
        level
        position
      }
    }
    fixedBudget
    pictures {
      body
      date
      author {
        birthdate
        snsLogin
        email
        email_verified
        name
        phone_number
        avatar
        level
        position
      }
      src
      title
      comments {
        id
        body
        date
        postId
      }
      numComments
      numLikes
      numShares
      topics
    }
    supports {
      id
      cProjectId
      date
      status
      title
      description
    }
    status
    syncGithub
    themeColor
  }
}
`;
export const onUpdateProject = `subscription OnUpdateProject {
  onUpdateProject {
    id
    proposer {
      birthdate
      snsLogin
      email
      email_verified
      name
      phone_number
      posts
      avatar
      level
      position
    }
    name
    description
    types
    topics
    deadlineOption
    startDuration
    endDuration
    manager
    personnel
    hasPlace
    place
    studyTopics
    studyMeeting
    studyTutor
    contestTopic
    contestProductDescription
    contestName
    contestDuedate
    contestObjectives
    seminarTopics
    seminarIsOnce
    seminarMeeting
    seminarPresenter
    shareCopyright
    agileHasBeen
    etcDescription
    request {
      id
      cProjectId
      project {
        id
        name
        description
        types
        topics
        deadlineOption
        startDuration
        endDuration
        manager
        personnel
        hasPlace
        place
        studyTopics
        studyMeeting
        studyTutor
        contestTopic
        contestProductDescription
        contestName
        contestDuedate
        contestObjectives
        seminarTopics
        seminarIsOnce
        seminarMeeting
        seminarPresenter
        shareCopyright
        agileHasBeen
        etcDescription
        fixedBudget
        status
        syncGithub
        themeColor
      }
      date
      requester {
        birthdate
        snsLogin
        email
        email_verified
        name
        phone_number
        avatar
        level
        position
      }
      hopePlaces
      material
      budget
      cookie
      extra
      status
    }
    activities {
      id
      projectName
      date
      type
      description
      contributors {
        birthdate
        snsLogin
        email
        email_verified
        name
        phone_number
        avatar
        level
        position
      }
    }
    contributors {
      birthdate
      snsLogin
      email
      email_verified
      name
      phone_number
      posts
      avatar
      level
      position
    }
    comments {
      id
      body
      date
      postId
      cProjectId
      project {
        id
        name
        description
        types
        topics
        deadlineOption
        startDuration
        endDuration
        manager
        personnel
        hasPlace
        place
        studyTopics
        studyMeeting
        studyTutor
        contestTopic
        contestProductDescription
        contestName
        contestDuedate
        contestObjectives
        seminarTopics
        seminarIsOnce
        seminarMeeting
        seminarPresenter
        shareCopyright
        agileHasBeen
        etcDescription
        fixedBudget
        status
        syncGithub
        themeColor
      }
      author {
        birthdate
        snsLogin
        email
        email_verified
        name
        phone_number
        avatar
        level
        position
      }
    }
    contents {
      id
      project {
        id
        name
        description
        types
        topics
        deadlineOption
        startDuration
        endDuration
        manager
        personnel
        hasPlace
        place
        studyTopics
        studyMeeting
        studyTutor
        contestTopic
        contestProductDescription
        contestName
        contestDuedate
        contestObjectives
        seminarTopics
        seminarIsOnce
        seminarMeeting
        seminarPresenter
        shareCopyright
        agileHasBeen
        etcDescription
        fixedBudget
        status
        syncGithub
        themeColor
      }
      body
      comments {
        id
        body
        date
        postId
      }
      author {
        birthdate
        snsLogin
        email
        email_verified
        name
        phone_number
        avatar
        level
      }
      date
      headerImgSrc
      isLike
      issueName
      numComments
      numLikes
      numShares
      themeColor
      title
      topics
      whoLike {
        birthdate
        snsLogin
        email
        email_verified
        name
        phone_number
        avatar
        level
      }
      contributors {
        birthdate
        snsLogin
        email
        email_verified
        name
        phone_number
        avatar
        level
        position
      }
    }
    fixedBudget
    pictures {
      body
      date
      author {
        birthdate
        snsLogin
        email
        email_verified
        name
        phone_number
        avatar
        level
        position
      }
      src
      title
      comments {
        id
        body
        date
        postId
      }
      numComments
      numLikes
      numShares
      topics
    }
    supports {
      id
      cProjectId
      date
      status
      title
      description
    }
    status
    syncGithub
    themeColor
  }
}
`;
export const onDeleteProject = `subscription OnDeleteProject {
  onDeleteProject {
    id
    proposer {
      birthdate
      snsLogin
      email
      email_verified
      name
      phone_number
      posts
      avatar
      level
      position
    }
    name
    description
    types
    topics
    deadlineOption
    startDuration
    endDuration
    manager
    personnel
    hasPlace
    place
    studyTopics
    studyMeeting
    studyTutor
    contestTopic
    contestProductDescription
    contestName
    contestDuedate
    contestObjectives
    seminarTopics
    seminarIsOnce
    seminarMeeting
    seminarPresenter
    shareCopyright
    agileHasBeen
    etcDescription
    request {
      id
      cProjectId
      project {
        id
        name
        description
        types
        topics
        deadlineOption
        startDuration
        endDuration
        manager
        personnel
        hasPlace
        place
        studyTopics
        studyMeeting
        studyTutor
        contestTopic
        contestProductDescription
        contestName
        contestDuedate
        contestObjectives
        seminarTopics
        seminarIsOnce
        seminarMeeting
        seminarPresenter
        shareCopyright
        agileHasBeen
        etcDescription
        fixedBudget
        status
        syncGithub
        themeColor
      }
      date
      requester {
        birthdate
        snsLogin
        email
        email_verified
        name
        phone_number
        avatar
        level
        position
      }
      hopePlaces
      material
      budget
      cookie
      extra
      status
    }
    activities {
      id
      projectName
      date
      type
      description
      contributors {
        birthdate
        snsLogin
        email
        email_verified
        name
        phone_number
        avatar
        level
        position
      }
    }
    contributors {
      birthdate
      snsLogin
      email
      email_verified
      name
      phone_number
      posts
      avatar
      level
      position
    }
    comments {
      id
      body
      date
      postId
      cProjectId
      project {
        id
        name
        description
        types
        topics
        deadlineOption
        startDuration
        endDuration
        manager
        personnel
        hasPlace
        place
        studyTopics
        studyMeeting
        studyTutor
        contestTopic
        contestProductDescription
        contestName
        contestDuedate
        contestObjectives
        seminarTopics
        seminarIsOnce
        seminarMeeting
        seminarPresenter
        shareCopyright
        agileHasBeen
        etcDescription
        fixedBudget
        status
        syncGithub
        themeColor
      }
      author {
        birthdate
        snsLogin
        email
        email_verified
        name
        phone_number
        avatar
        level
        position
      }
    }
    contents {
      id
      project {
        id
        name
        description
        types
        topics
        deadlineOption
        startDuration
        endDuration
        manager
        personnel
        hasPlace
        place
        studyTopics
        studyMeeting
        studyTutor
        contestTopic
        contestProductDescription
        contestName
        contestDuedate
        contestObjectives
        seminarTopics
        seminarIsOnce
        seminarMeeting
        seminarPresenter
        shareCopyright
        agileHasBeen
        etcDescription
        fixedBudget
        status
        syncGithub
        themeColor
      }
      body
      comments {
        id
        body
        date
        postId
      }
      author {
        birthdate
        snsLogin
        email
        email_verified
        name
        phone_number
        avatar
        level
      }
      date
      headerImgSrc
      isLike
      issueName
      numComments
      numLikes
      numShares
      themeColor
      title
      topics
      whoLike {
        birthdate
        snsLogin
        email
        email_verified
        name
        phone_number
        avatar
        level
      }
      contributors {
        birthdate
        snsLogin
        email
        email_verified
        name
        phone_number
        avatar
        level
        position
      }
    }
    fixedBudget
    pictures {
      body
      date
      author {
        birthdate
        snsLogin
        email
        email_verified
        name
        phone_number
        avatar
        level
        position
      }
      src
      title
      comments {
        id
        body
        date
        postId
      }
      numComments
      numLikes
      numShares
      topics
    }
    supports {
      id
      cProjectId
      date
      status
      title
      description
    }
    status
    syncGithub
    themeColor
  }
}
`;
export const onCreateRequest = `subscription OnCreateRequest {
  onCreateRequest {
    id
    cProjectId
    project {
      id
      proposer {
        birthdate
        snsLogin
        email
        email_verified
        name
        phone_number
        avatar
        level
        position
      }
      name
      description
      types
      topics
      deadlineOption
      startDuration
      endDuration
      manager
      personnel
      hasPlace
      place
      studyTopics
      studyMeeting
      studyTutor
      contestTopic
      contestProductDescription
      contestName
      contestDuedate
      contestObjectives
      seminarTopics
      seminarIsOnce
      seminarMeeting
      seminarPresenter
      shareCopyright
      agileHasBeen
      etcDescription
      request {
        id
        cProjectId
        date
        hopePlaces
        material
        budget
        cookie
        extra
        status
      }
      activities {
        id
        projectName
        date
        type
        description
      }
      contributors {
        birthdate
        snsLogin
        email
        email_verified
        name
        phone_number
        avatar
        level
        position
      }
      comments {
        id
        body
        date
        postId
        cProjectId
      }
      contents {
        id
        body
        date
        headerImgSrc
        isLike
        issueName
        numComments
        numLikes
        numShares
        themeColor
        title
        topics
      }
      fixedBudget
      pictures {
        body
        date
        src
        title
        numComments
        numLikes
        numShares
        topics
      }
      supports {
        id
        cProjectId
        date
        status
        title
        description
      }
      status
      syncGithub
      themeColor
    }
    date
    requester {
      birthdate
      snsLogin
      email
      email_verified
      name
      phone_number
      posts
      avatar
      level
      position
    }
    hopePlaces
    material
    budget
    cookie
    extra
    status
  }
}
`;
export const onUpdateRequest = `subscription OnUpdateRequest {
  onUpdateRequest {
    id
    cProjectId
    project {
      id
      proposer {
        birthdate
        snsLogin
        email
        email_verified
        name
        phone_number
        avatar
        level
        position
      }
      name
      description
      types
      topics
      deadlineOption
      startDuration
      endDuration
      manager
      personnel
      hasPlace
      place
      studyTopics
      studyMeeting
      studyTutor
      contestTopic
      contestProductDescription
      contestName
      contestDuedate
      contestObjectives
      seminarTopics
      seminarIsOnce
      seminarMeeting
      seminarPresenter
      shareCopyright
      agileHasBeen
      etcDescription
      request {
        id
        cProjectId
        date
        hopePlaces
        material
        budget
        cookie
        extra
        status
      }
      activities {
        id
        projectName
        date
        type
        description
      }
      contributors {
        birthdate
        snsLogin
        email
        email_verified
        name
        phone_number
        avatar
        level
        position
      }
      comments {
        id
        body
        date
        postId
        cProjectId
      }
      contents {
        id
        body
        date
        headerImgSrc
        isLike
        issueName
        numComments
        numLikes
        numShares
        themeColor
        title
        topics
      }
      fixedBudget
      pictures {
        body
        date
        src
        title
        numComments
        numLikes
        numShares
        topics
      }
      supports {
        id
        cProjectId
        date
        status
        title
        description
      }
      status
      syncGithub
      themeColor
    }
    date
    requester {
      birthdate
      snsLogin
      email
      email_verified
      name
      phone_number
      posts
      avatar
      level
      position
    }
    hopePlaces
    material
    budget
    cookie
    extra
    status
  }
}
`;
export const onDeleteRequest = `subscription OnDeleteRequest {
  onDeleteRequest {
    id
    cProjectId
    project {
      id
      proposer {
        birthdate
        snsLogin
        email
        email_verified
        name
        phone_number
        avatar
        level
        position
      }
      name
      description
      types
      topics
      deadlineOption
      startDuration
      endDuration
      manager
      personnel
      hasPlace
      place
      studyTopics
      studyMeeting
      studyTutor
      contestTopic
      contestProductDescription
      contestName
      contestDuedate
      contestObjectives
      seminarTopics
      seminarIsOnce
      seminarMeeting
      seminarPresenter
      shareCopyright
      agileHasBeen
      etcDescription
      request {
        id
        cProjectId
        date
        hopePlaces
        material
        budget
        cookie
        extra
        status
      }
      activities {
        id
        projectName
        date
        type
        description
      }
      contributors {
        birthdate
        snsLogin
        email
        email_verified
        name
        phone_number
        avatar
        level
        position
      }
      comments {
        id
        body
        date
        postId
        cProjectId
      }
      contents {
        id
        body
        date
        headerImgSrc
        isLike
        issueName
        numComments
        numLikes
        numShares
        themeColor
        title
        topics
      }
      fixedBudget
      pictures {
        body
        date
        src
        title
        numComments
        numLikes
        numShares
        topics
      }
      supports {
        id
        cProjectId
        date
        status
        title
        description
      }
      status
      syncGithub
      themeColor
    }
    date
    requester {
      birthdate
      snsLogin
      email
      email_verified
      name
      phone_number
      posts
      avatar
      level
      position
    }
    hopePlaces
    material
    budget
    cookie
    extra
    status
  }
}
`;
export const onCreateHistory = `subscription OnCreateHistory {
  onCreateHistory {
    id
    date
    body
    author {
      birthdate
      snsLogin
      email
      email_verified
      name
      phone_number
      posts
      avatar
      level
    }
  }
}
`;
export const onUpdateHistory = `subscription OnUpdateHistory {
  onUpdateHistory {
    id
    date
    body
    author {
      birthdate
      snsLogin
      email
      email_verified
      name
      phone_number
      posts
      avatar
      level
    }
  }
}
`;
export const onDeleteHistory = `subscription OnDeleteHistory {
  onDeleteHistory {
    id
    date
    body
    author {
      birthdate
      snsLogin
      email
      email_verified
      name
      phone_number
      posts
      avatar
      level
    }
  }
}
`;
