// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:064a03ba-75e1-4625-8fba-330b3121ed78",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_8641GyPB5",
    "aws_user_pools_web_client_id": "3q12a6lc7ha8mlub12anm83mo7",
    "aws_mobile_analytics_app_id": "fd743d6ddd674577b846302b902fff4d",
    "aws_mobile_analytics_app_region": "us-west-2",
    "aws_appsync_graphqlEndpoint": "https://vkyatt3tsjcuzdjtva2pfqy3va.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "bucket-boot4dim",
    "aws_user_files_s3_bucket_region": "us-west-2",
    "aws_dynamodb_all_tables_region": "us-west-2",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "dynamoBoot4Dim",
            "region": "us-west-2"
        }
    ]
};


export default awsmobile;
